version: '3.9'

services:
  web:
  image: php:apache
  container_name: servidor_web
  volumes:
    - ./web:/var/www/html
    - ./config/apache2.conf:/etc/apache2/apache2.conf
  ports:
    - "80:80"
  environment:
    - APACHE_RUN_USER=${APACHE_RUN_USER}
    - APACHE_RUN_GROUP=${APACHE_RUN_GROUP}
  command: apache2-foreground

  db:
    image: mariadb
    container_name: servidor_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  ftp:
    image: stilliard/pure-ftpd
    container_name: servidor_ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=${PUBLICHOST}
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - FTP_USER_HOME=${FTP_USER_HOME}

  mail:
    image: tvial/docker-mailserver:latest
    container_name: servidor_correo
    hostname: mail
    domainname: example.com
    env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - ./config:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - SSL_TYPE=none

volumes:
  maildata:
  mailstate:
  maillogs:
  config:
