version: '3.9'

services:
  web:
    build: .
    container_name: servidor_web
    ports:
      - "80:80"
    environment:
      - APACHE_RUN_USER=${APACHE_RUN_USER:-www-data}
      - APACHE_RUN_GROUP=${APACHE_RUN_GROUP:-www-data}
    command: /bin/bash -c "mkdir -p /etc/apache2/logs && apache2-foreground"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - webnet

  db:
    image: mariadb:latest
    container_name: servidor_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - webnet

  ftp:
    image: stilliard/pure-ftpd:latest
    container_name: servidor_ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=${PUBLICHOST}
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - FTP_USER_HOME=${FTP_USER_HOME}
    networks:
      - webnet

networks:
  webnet:
